# ***Scikit-learn (Datasets):***

Trabajaremos con datasets, los cuales son parecidos a los diccionarios. Se los puede crear o ya vienen datasets predeterminados. Se componen de 4 partes: DESCR, data, feature_names y target. En Spider aparece como de tipo utils.Bunch ya que dentro tiene string, float y listas.


In [3]:
from sklearn import datasets #Importa la función para llamar datasets de la libreria scikit-learn.

***Función .load_nombredataset():*** carga un dataset

In [4]:
iris = datasets.load_iris()
iris

{'DESCR': 'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ==

In [10]:
iris.data #Muestra la parte data de Iris

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
iris.DESCR #Muestra la descripición de iris

'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ============

In [12]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model #Importa la función que permite cargar datasets en python y la que permite hacer un modelo lineal

Creación de una regresión lineal:

***Función linear_model.LinearRegression():***

In [17]:
# Crea una regresión lineal
regr = linear_model.LinearRegression()
regr

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

Ahora debemos trabajar la regresión lineal para que se ajuste a algunos valores que queramos predecir con ella.

Primero, armamos conjuntos de entrenamiento y prueba a partir de los datos.

In [14]:
iris_X = iris.data[:, np.newaxis, 2] #Agarra una parte del dataset(data) tomando todas las filas y sólo los valores de la columna 2
# Divide a data en set de entrenamiento y testeo
iris_X_train = iris_X[:-20] #Para entrenar el programa tomo todos los valores menos los últimos 20
iris_X_test = iris_X[-20:] #Para testear el programa tomo los últimos 20 valores
# Divide a target en set de entrenamiento y testeo
iris_y_train = iris.target[:-20]   #Agarra la parte target del dataset difiniendo entrenamiento y pruea de la misma manera que antes
iris_y_test = iris.target[-20:]
iris_y_test

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

***Función .fit():*** Le da formato a la regresión lineal con los datos de entrenamiento que tenemos usan el método de cuadrados mínimos.

In [31]:
regr.fit(iris_X_train, iris_y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

***Función .predict():*** predice que valores de Y darian con estos valores de X ingresados para testearlo. Hago que funcione la regresión.

In [37]:
iris_y_pred = regr.predict(iris_X_test)
iris_y_pred

array([1.9399036 , 2.06584467, 1.73000182, 1.52010003, 1.73000182,
       1.9399036 , 1.73000182, 1.68802146, 1.39415896, 1.6460411 ,
       1.73000182, 1.52010003, 1.52010003, 1.85594289, 1.77198217,
       1.56208039, 1.47811968, 1.56208039, 1.6460411 , 1.52010003])

***Función .predict():*** 

In [33]:
regr.coef_ #No se bien que hace pero al parecer da el valor de la pendiente de la recta obtenida mediante cuadrados mínimos.

array([0.41980357])

In [38]:
regr.intercept_ #Dá la ordenada al origen de la recta obtenida mediante cuadrados mínimos.

-0.620898155846808

In [26]:
from sklearn.metrics import mean_squared_error, r2_score #Importa las funciones para medir el error cuadrático medio y la varianza.

***Función mean_squared_error():*** Calcula el error cuadrático medio

In [34]:
print("Mean squared error: %.2f" % mean_squared_error(iris_y_test, iris_y_pred))

Mean squared error: 0.13


***Función r2_score():*** Calcula la varianza entre el valor predicho y el valor real (1 es una predicción perfecta).

In [35]:
print('Variance score: %.2f' % r2_score(iris_y_test, iris_y_pred))

Variance score: 0.00


Al parecer, fue una predicción muy mala.

Agarro toda la columna 2 en la data de iris:

In [5]:
iris_L = iris.data[:, 2]
iris_L

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1])

**Método KNN:**

In [10]:
from sklearn import neighbors #Importo la función KNN.
n_neighbors = 15 #Defino la cantidad de vecinos admitidos.
clf = neighbors.KNeighborsClassifier(n_neighbors) #Con esa cantidad armo el método
clf.fit(iris_X_train, iris_y_train) #Le doy forma con mis datos de entrenamiento.

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=15, p=2,
           weights='uniform')

In [13]:
iris_y_pred = clf.predict(iris_X_test) #Ahora armo mi predicción.
iris_y_pred

array([2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
print("Tasa:",np.mean(iris_y_test == iris_y_pred)) #Muestra la coincidencia en la predicción.

Tasa: 0.95
