REPASO PRIMER PARCIAL: Numerical Python (NumPy)

In [3]:
import numpy as np # Es una extensión de Python que otorga un mayor soporte para el tratamiento de matrices y vectores

Trabajaremos con arreglos (son vectores y matrices)

Función np.array () para crear un arreglo:

In [6]:
mylist = [1, 2, 3] # Crea una lista
x = np.array(mylist) # Convierte la lista en un arreglo de Numpy
x #Muestra el arreglo

array([1, 2, 3])

In [8]:
y = np.array([4, 5, 6]) #Directamente pasa a arreglo Numpy una lista en la cual definida en el mismo código
y

array([4, 5, 6])

Función para crear un arreglo multidimensional

In [11]:
m = np.array([[7, 8, 9], [10, 11, 12]]) # Crea un arreglo multidimensional, una matriz
m

array([[ 7,  8,  9],
       [10, 11, 12]])

Función .shape para conocer las dimensiones de un arreglo

In [12]:
m.shape # Indica la dimensión de mi arreglo en filas y columnas

(2, 3)

Función np.arange() para crear un arreglo con las condiciones pedidas

In [16]:
n = np.arange(0, 30, 2) # Crea un arreglo que empieza en cero y va saltando de 2 en dos hasta llegar a 29 ya que python siempre toma un valor menos
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

Función .reshape() para cambiar las dimensiones de un arreglo

In [18]:
n = n.reshape(3, 5) # Le da un nuevo formato a un determinado arreglo conservando los mismos datos
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

Función np.linspace() para crear un arreglo equiespaciado.

In [20]:
o = np.linspace(0, 4, 9) # Regresa 9 números equiespaciados en el intervalo entre 0 y 4. en este caso si toma como último número al definido.
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

Función .resize() para rehacer una matrz con las dimesiones pedidas

In [21]:
o.resize(3, 3) #Rehace una matriz con las dimensiones pedidas entre el valor máximo y el mínimo del arreglo definiendo los nuevos valores que sean necesarios.
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

Función .Ones

In [22]:
np.ones((3, 2)) # Da como resultado una matriz con las dimensiones pedidas pero que está llena de unos.

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Función .Zeros

In [23]:
np.zeros((2, 3)) # Da como resultado una matriz de las dimensiones pedidas que esta completa por ceros.

array([[0., 0., 0.],
       [0., 0., 0.]])

Función .eye

In [24]:
np.eye(3) # Da una matriz que esta compuesta por unos en su diagonal principal y ceros en el resto de la misma.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Función .diag

In [25]:
np.diag(y) # Da como resultado un arreglo que posee en su diagonal principal los números que posee el arreglo previamente determinado.

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

Función .Tile

In [28]:
np.tile(o,3) # Crea un arreglo repitiendo el número de veces que se le indique un arreglo previamente determinado.

array([[0. , 0.5, 1. , 0. , 0.5, 1. , 0. , 0.5, 1. ],
       [1.5, 2. , 2.5, 1.5, 2. , 2.5, 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 3. , 3.5, 4. , 3. , 3.5, 4. ]])

Creación de un arreglo repitiendo una lista

In [29]:
np.array([1, 2, 3] * 3) #Crea un arreglo repitiendo las veces indicadas el arrglo que se le defina.

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

Función np.repeat

In [30]:
np.repeat([1, 2, 3], 3) #Repite las veces indicadas los valores que se definen.

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

<br>
#### Combinando arreglos

In [33]:
p = np.ones([2, 3], int) #Genera un arreglo de unos con las dimensiones indicadas y los unos los toma como un valor entero
p

array([[1, 1, 1],
       [1, 1, 1]])

Función np.vstack

In [34]:
np.vstack([p, 2*p]) #Realiza un arreglo que contenga al arreglo predefinido y al mismo con una operacion realizada en él. En sí la función realiza un arreglo "pegando" otros de manera VERTICAL.

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

Función np.hstack

In [35]:
np.hstack([p, 2*p]) #Realiza un arreglo que contenga al arreglo predefinido y al mismo con una operacion realizada en él. En sí la función realiza un arreglo "pegando" otros de manera HORIZONTAL.

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

<br>
## Operaciones

`+`, `-`, `*`, `/`, `**` se pueden usar sumas, restas, multiplicaciones, divisiones y potenciasion.

In [36]:
print(x + y) # Suma los siguientes arreglos predeterminados y muestra en pantalla el resultado  [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # Resta y mue los siguientes arreglos predeterminados y muestra en pantalla el resultado  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [37]:
print(x * y) # Multiplica los siguientes arreglos predeterminados y muestra en pantalla el resultado  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # Divide los siguientes arreglos predeterminados y muestra en pantalla el resultado         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [38]:
print(x**2) # Aplica exponencial los siguientes arreglos predeterminados y muestra en pantalla el resultado  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


<br>
**Producto Interno:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [39]:
x.dot(y) #Realiza el producto interno de las matrices predeterminadas  1*4 + 2*5 + 3*6

32

In [44]:
z = np.array([y, y**2])
print(len(z)) # Devuelve el número de filas de la cadena (en teoria también lo puede hacer con caracteres)

2


Ejercicio de la Transpuesta

In [45]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

Conozco las dimensiones antes de trasponer

In [46]:
z.shape

(2, 3)

Función Transpuesta

In [47]:
z.T # Realiza la transpuesta de un arreglo

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

El número de filas y columnas se invirtieron

In [48]:
z.T.shape

(3, 2)

Función .dtype

In [105]:
z.dtype # Indica el tipo de los elementos.

dtype('float32')

Función .astype()

In [54]:
z = z.astype('f') #Convierte las componetes del arreglo predeterminado en variables flotantes
z.dtype # Indica que tipo de arreglo es

dtype('float32')

Unión de listas

In [58]:
lista=['a']
listab=[1]
print (lista + listab) #Muestra en pantalla una nueva lista formada por otras 2 listas.

['a', 1]


<br>
## Funciones Matemáticas

In [59]:
a = np.array([-4, -2, 1, 3, 5]) #Genera un arreglo

In [60]:
a.sum() #Suma todas las componentes del arreglo

3

In [61]:
a.max() #Muestra el valor máximo del arreglo

5

In [62]:
a.min() #Muestra el valor mínimo del arreglo

-4

In [63]:
a.mean() #Muestra el promedio de los valores del arreglo

0.6

In [64]:
a.std() #Muestra la desviación estándar de los valores del arreglo

3.2619012860600183

<br>
Las funciones`argmax` y `argmin` muestran las posiciones de los valores máximos y mínimos del arrego.

In [65]:
a.argmax() #Regresa la posición del arreglo donde se encuentra el valor máximo

4

In [66]:
a.argmin() #Regresa la posición del arrgelo donde se encuentra el valor mínimo

0

<br>
## Indexar/cortar

In [71]:
s = np.arange(13)**2 #Crea un arreglo que contiene todos los cuadrados hasta el cuadrado de 12.
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

Para pedir un valor de una determinada posición

In [76]:
s[0], s[4], s[-1] # Regresa los valores en las posiciones pedidas. en el último caso el negativo implica que se empezará a contar de atrás para adelante del arreglo.

(0, 16, 144)

<br>
Usa `:` para indicar un rango. `array[start:stop]`

In [77]:
s[1:5] #Muestra los valores que están desde la posición 1 a la 4

array([ 1,  4,  9, 16], dtype=int32)

<br>
Usa el valor negativo para contar desde atras

In [78]:
s[-4:] #Muestra los últimos 4 valores del arreglo

array([ 81, 100, 121, 144], dtype=int32)

<br>
Un segundo `:` indica el paso. `array[start:stop:stepsize]`

In [81]:
s[-5::-2] #empiezo desde el quinto valor del arreglo contando desde el final y voy saltando valores de a 2 posiciones hasta el inicio.

array([64, 36, 16,  4,  0], dtype=int32)

<br>
Arreglo multidimensional

In [4]:
r = np.arange(36) #Creará un arreglo que llegue hasta el número 35.
r.resize((6, 6)) #Lo ubicará en una matriz 6x6
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br>
Para buscar el valor en una intersección: `array[fila, columna]`

In [5]:
r[2, 2] #muestra el valor que está en lainterseccion de la tercera fila (empieza a contar desde cero) y la tercera columna (empieza a contar desde cero).

14

<br>
Usa : para seleccionar un rango de filas o columnas

In [84]:
r[3, 3:6] #Muestra los valores que están entre la cuarta fila (empieza a contar desde cero) y las columnas desde la cuarta a la sexta columna.

array([21, 22, 23])

In [85]:
r[:2, :-1] #Muestra las filas 1 y 2 (contando luegares serian la cero y la 1) y todas las columnas menos la última.

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [86]:
r[-1, ::2] #Elijo de la última fila los valores de las columnas saltando de a 2 lugares.

array([30, 32, 34])

In [87]:
r[r > 30] #Muestra todos los valores del arreglo que son mayores a 30.

array([31, 32, 33, 34, 35])

In [88]:
np.where(r > 30) #Me regresa la posición de donde se encuentran los valores que le pido

(array([5, 5, 5, 5, 5], dtype=int32), array([1, 2, 3, 4, 5], dtype=int32))

In [89]:
r[r > 30] = 30 #Le asigno el valor de 30 a todos los valores que sean mayores a 30.
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
## Copiando información

In [90]:
r2 = r[:3,:3] #Genera un arreglo a partir de uno de mayor dimensión.
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [93]:
r2[:] = 0 #Le asigno a todo el arreglo el valor cero
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<br>
`r` también cambió!

In [94]:
r #El arreglo r2 era parte de el arreglo r. No era una copia.

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [95]:
r_copy = r.copy() #Crea una copia del arreglo r.
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
Cuando la copia se modifica no lo hace el archivo original

In [96]:
r_copy[:] = 10 #Al modificar la copia no se modifica el original.
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


<br>
### Iterando sobre arreglos (aplicando bucles)

Función np.random.randint()

In [6]:
test = np.random.randint(0, 10, (4,3)) #Crea un arreglo de valores random (enteros) que se encuentren entre los valores 0 y 9. Además, indica la dimensión que tendrá ese arreglo.
test

array([[3, 3, 8],
       [9, 9, 1],
       [4, 1, 6],
       [0, 5, 0]])

<br>
Iterando por columnas:

In [98]:
for row in test: #Muestra las filas de la matriz test y no para hasta que estén todas.
    print(row)

[0 6 7]
[9 6 0]
[4 9 0]
[9 4 6]


<br>
Iterando por índice:

In [99]:
for i in range(len(test)): #Va mostrando las filas que componen a la matriz (lo mismo que lo de arriba pero escrito de manera diferente).
    print(test[i])

[0 6 7]
[9 6 0]
[4 9 0]
[9 4 6]


<br>
Iterando ambos:

In [7]:
for i, row in enumerate(test): #Enumera y muestra las filas de la matriz.
    print('columna', i, 'es', row)

columna 0 es [3 3 8]
columna 1 es [9 9 1]
columna 2 es [4 1 6]
columna 3 es [0 5 0]


In [103]:
test2 = test**2 #Crea un arreglo que tiene como componentes los cuadrados de un arreglo9 predeterminado.
test2

array([[ 0, 36, 49],
       [81, 36,  0],
       [16, 81,  0],
       [81, 16, 36]], dtype=int32)

Función zip

## for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

In [104]:
for i, j in zip(test, test2): #La función zip toma los elementos iésimos de 2 listas y los une en tuplas. En esta función se la usa para relacionar estos valores y sumarlos. Suma al valor con su cuadrado.
    print(i,'+',j,'=',i+j)

[0 6 7] + [ 0 36 49] = [ 0 42 56]
[9 6 0] + [81 36  0] = [90 42  0]
[4 9 0] + [16 81  0] = [20 90  0]
[9 4 6] + [81 16 36] = [90 20 42]


Función np.where()

Escribir un par de líneas de código en python que, dado un np.array *x*, devuelva los elementos de *x* mayores que 10 y sus coordenadas.

In [2]:
import numpy as np
m = np.array([[0, 10, 20], [20, 30, 40]]) # Se ingresa el arreglo
j=m[m>10]
k=np.where(m>10)
print("Mi arreglo:\n")
print(m)
print("\n")
print("Valores mayores que 10:\n")
print(j)
print("\n")
print("Donde se encuentran esos valores mayores que 10:\n")
print(k)

Mi arreglo:

[[ 0 10 20]
 [20 30 40]]


Valores mayores que 10:

[20 20 30 40]


Donde se encuentran esos valores mayores que 10:

(array([0, 1, 1, 1], dtype=int32), array([2, 0, 1, 2], dtype=int32))


Redondear decimales

In [4]:
a=np.round(0.33738333,decimals=2)
a

0.34

Armar una lista

In [5]:
year_cols=['Y'+str(y) for y in np.arange(1961,2017)] #Arma una lista con los valores string de los años desde 1961 hasta el 2016
year_cols

['Y1961',
 'Y1962',
 'Y1963',
 'Y1964',
 'Y1965',
 'Y1966',
 'Y1967',
 'Y1968',
 'Y1969',
 'Y1970',
 'Y1971',
 'Y1972',
 'Y1973',
 'Y1974',
 'Y1975',
 'Y1976',
 'Y1977',
 'Y1978',
 'Y1979',
 'Y1980',
 'Y1981',
 'Y1982',
 'Y1983',
 'Y1984',
 'Y1985',
 'Y1986',
 'Y1987',
 'Y1988',
 'Y1989',
 'Y1990',
 'Y1991',
 'Y1992',
 'Y1993',
 'Y1994',
 'Y1995',
 'Y1996',
 'Y1997',
 'Y1998',
 'Y1999',
 'Y2000',
 'Y2001',
 'Y2002',
 'Y2003',
 'Y2004',
 'Y2005',
 'Y2006',
 'Y2007',
 'Y2008',
 'Y2009',
 'Y2010',
 'Y2011',
 'Y2012',
 'Y2013',
 'Y2014',
 'Y2015',
 'Y2016']

Funciones para encontrar y tratar los NaN en un objeto

In [6]:
import pandas as pd #Primero importo el archivo con pandas
fname = 'C:/Users/Nancy/Desktop/Phyton/Clase 4/sfba_2014_04.csv'
df = pd.read_csv(fname,parse_dates=['Time'],index_col='Time') 
df.head(3)

SF   BA
Time                           
2014-04-01 00:00:00  178.0  134
2014-04-01 01:00:00  161.0  116
2014-04-01 02:00:00  150.0  107

In [9]:
np.isnan(df).head(3) #Me otorga un vector donde False es que no hay NaN y True es que si lo hay.

SF     BA
Time                             
2014-04-01 00:00:00  False  False
2014-04-01 01:00:00  False  False
2014-04-01 02:00:00  False  False

In [10]:
np.where(np.isnan(df)) #Indica en que posiciones están los NaN en el dataframe df. (más bien indica las posiciones de los True)

(array([456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467],
       dtype=int32), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32))

In [12]:
df.isnull().head() #Realiza un proceso similar a isnan

SF     BA
Time                             
2014-04-01 00:00:00  False  False
2014-04-01 01:00:00  False  False
2014-04-01 02:00:00  False  False
2014-04-01 03:00:00  False  False
2014-04-01 04:00:00  False  False

In [15]:
print("Cantidad de datos faltantes en las columnas:") #Cuenta la cantidad de datos faltantes por columnas
df.isnull().sum()

Cantidad de datos faltantes en las columnas:


SF    12
BA     0
dtype: int64